package darkness.generator.scripts.uka19

import darkness.generator.api.BulbRGB
import java.awt.Color
import java.util.*

//

class UKEnavnBetydningPæreForPære: BaseScript() {
    override suspend fun run() {
        super.run()

        val gul = Color(246, 255, 0)
        val gul2 = Color(140, 255, 0)
        val grønn1 = Color(77, 255, 0)
        val grønn2 = Color(0, 255, 51)
        val grønn3 = Color(0, 255, 145)
        val blå1 = Color(0, 255, 221)
        val blå2 = Color(0, 225, 255)

        val blå3 = Color(0, 106, 255)
        val blå4 = Color(38, 0, 255)
        val lilla1 = Color(119, 0, 255)
        val lilla2 = Color(191, 0, 255)
        val rosa1 = Color(225, 0, 255)
        val rosa2 = Color(255, 0, 234)
        val rosa3 = Color(255, 0, 162)

        //viville

        //v
        set(bulb(0), gul)
        skip(1)
        set(bulb(1), gul)
        skip(1)
        set(bulb(2), gul)
        skip(1)
        set(bulb(3), gul)
        skip(1)
        set(bulb(4), gul)
        skip(1)
        set(bulb(9), gul)
        skip(1)
        set(bulb(5), gul)
        skip(1)
        set(bulb(6), gul)
        skip(1)
        set(bulb(7), gul)
        skip(1)
        set(bulb(8), gul)
        skip(1)

        //i
        set(bulb(10),gul2)
        skip(1)
        set(bulb(11), gul2)
        skip(1)
        set(bulb(12), gul2)
        skip(1)
        set(bulb(13), gul2)
        skip(1)
        set(bulb(14), gul2)
        skip(1)

        //v
        set(bulb(20), grønn1)
        skip(1)
        set(bulb(21), grønn1)
        skip(1)
        set(bulb(22), grønn1)
        skip(1)
        set(bulb(23), grønn1)
        skip(1)
        set(bulb(27), grønn1)
        skip(1)
        set(bulb(24), grønn1)
        skip(1)
        set(bulb(25), grønn1)
        skip(1)
        set(bulb(26), grønn1)
        skip(1)

        //i
        set(bulb(30), grønn2)
        skip(1)
        set(bulb(31), grønn2)
        skip(1)
        set(bulb(32), grønn2)
        skip(1)
        set(bulb(33), grønn2)
        skip(1)
        set(bulb(34), grønn2)
        skip(1)

        //l
        set(bulb(40), grønn3)
        skip(1)
        set(bulb(41), grønn3)
        skip(1)
        set(bulb(42), grønn3)
        skip(1)
        set(bulb(43), grønn3)
        skip(1)
        set(bulb(44), grønn3)
        skip(1)
        set(bulb(45), grønn3)
        skip(1)

        //l
        set(bulb(50), blå1)
        skip(1)
        set(bulb(51), blå1)
        skip(1)
        set(bulb(52), blå1)
        skip(1)
        set(bulb(53), blå1)
        skip(1)
        set(bulb(54), blå1)
        skip(1)

        //e
        set(bulb(67), blå2)
        skip(1)
        set(bulb(66), blå2)
        skip(1)
        set(bulb(65), blå2)
        skip(1)
        set(bulb(64), blå2)
        skip(1)
        set(bulb(63), blå2)
        skip(1)
        set(bulb(62), blå2)
        skip(1)
        set(bulb(61), blå2)
        skip(1)
        set(bulb(60), blå2)
        skip(1)

        set(bulb(68), blå2)
        skip(1)
        set(bulb(69), blå2)
        skip(1)

        skip(40)


        //vi-ville
        //v
        set(bulb(0), gul)
        skip(1)
        set(bulb(1), gul)
        skip(1)
        set(bulb(2), gul)
        skip(1)
        set(bulb(3), gul)
        skip(1)
        set(bulb(4), gul)
        skip(1)
        set(bulb(9), gul)
        skip(1)
        set(bulb(5), gul)
        skip(1)
        set(bulb(6), gul)
        skip(1)
        set(bulb(7), gul)
        skip(1)
        set(bulb(8), gul)
        skip(1)

        //i
        set(bulb(10),gul)
        skip(1)
        set(bulb(11), gul)
        skip(1)
        set(bulb(12), gul)
        skip(1)
        set(bulb(13), gul)
        skip(1)
        set(bulb(14), gul)
        skip(1)

        //v
        set(bulb(20), blå2)
        skip(1)
        set(bulb(21), blå2)
        skip(1)
        set(bulb(22), blå2)
        skip(1)
        set(bulb(23), blå2)
        skip(1)
        set(bulb(27), blå2)
        skip(1)
        set(bulb(24), blå2)
        skip(1)
        set(bulb(25), blå2)
        skip(1)
        set(bulb(26), blå2)
        skip(1)

        //i
        set(bulb(30), blå2)
        skip(1)
        set(bulb(31), blå2)
        skip(1)
        set(bulb(32), blå2)
        skip(1)
        set(bulb(33), blå2)
        skip(1)
        set(bulb(34), blå2)
        skip(1)

        //l
        set(bulb(40), blå2)
        skip(1)
        set(bulb(41), blå2)
        skip(1)
        set(bulb(42), blå2)
        skip(1)
        set(bulb(43), blå2)
        skip(1)
        set(bulb(44), blå2)
        skip(1)
        set(bulb(45), blå2)
        skip(1)

        //l
        set(bulb(50), blå2)
        skip(1)
        set(bulb(51), blå2)
        skip(1)
        set(bulb(52), blå2)
        skip(1)
        set(bulb(53), blå2)
        skip(1)
        set(bulb(54), blå2)
        skip(1)

        //e
        set(bulb(67), blå2)
        skip(1)
        set(bulb(66), blå2)
        skip(1)
        set(bulb(65), blå2)
        skip(1)
        set(bulb(64), blå2)
        skip(1)
        set(bulb(63), blå2)
        skip(1)
        set(bulb(62), blå2)
        skip(1)
        set(bulb(61), blå2)
        skip(1)
        set(bulb(60), blå2)
        skip(1)
        set(bulb(68),0,0,0)
        skip(1)
        set(bulb(69), 0, 0, 0)
        skip(1)

        skip(40)

        //vi-vil-le
        //v
        set(bulb(0), gul)
        skip(1)
        set(bulb(1), gul)
        skip(1)
        set(bulb(2), gul)
        skip(1)
        set(bulb(3), gul)
        skip(1)
        set(bulb(4), gul)
        skip(1)
        set(bulb(9), gul)
        skip(1)
        set(bulb(5), gul)
        skip(1)
        set(bulb(6), gul)
        skip(1)
        set(bulb(7), gul)
        skip(1)
        set(bulb(8), gul)
        skip(1)

        //i
        set(bulb(10),gul)
        skip(1)
        set(bulb(11), gul)
        skip(1)
        set(bulb(12), gul)
        skip(1)
        set(bulb(13), gul)
        skip(1)
        set(bulb(14), gul)
        skip(1)

        //v
        set(bulb(20), rosa3)
        skip(1)
        set(bulb(21), rosa3)
        skip(1)
        set(bulb(22), rosa3)
        skip(1)
        set(bulb(23), rosa3)
        skip(1)
        set(bulb(27), rosa3)
        skip(1)
        set(bulb(24), rosa3)
        skip(1)
        set(bulb(25), rosa3)
        skip(1)
        set(bulb(26), rosa3)
        skip(1)

        //i
        set(bulb(30), rosa3)
        skip(1)
        set(bulb(31), rosa3)
        skip(1)
        set(bulb(32), rosa3)
        skip(1)
        set(bulb(33), rosa3)
        skip(1)
        set(bulb(34), rosa3)
        skip(1)

        //l
        set(bulb(40), rosa3)
        skip(1)
        set(bulb(41), rosa3)
        skip(1)
        set(bulb(42), rosa3)
        skip(1)
        set(bulb(43), rosa3)
        skip(1)
        set(bulb(44), rosa3)
        skip(1)
        set(bulb(45), rosa3)
        skip(1)

        //l
        set(bulb(50), blå2)
        skip(1)
        set(bulb(51), blå2)
        skip(1)
        set(bulb(52), blå2)
        skip(1)
        set(bulb(53), blå2)
        skip(1)
        set(bulb(54), blå2)
        skip(1)

        //e
        set(bulb(67), blå2)
        skip(1)
        set(bulb(66), blå2)
        skip(1)
        set(bulb(65), blå2)
        skip(1)
        set(bulb(64), blå2)
        skip(1)
        set(bulb(63), blå2)
        skip(1)
        set(bulb(62), blå2)
        skip(1)
        set(bulb(61), blå2)
        skip(1)
        set(bulb(60), blå2)
        skip(1)

        skip(40)
        }
    }
